/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import cinetudo.Sala;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author joao
 */
public class ConsultarSala extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConsultarSala
     */
    public ConsultarSala() {
        initComponents();
        fillCb();
        
    }
    
    public void fillCb()
    {
        ArrayList<cinetudo.Cinema> c2 = new ArrayList<>();
        cinetudo.Cinema c1 = new cinetudo.Cinema();
        c2 = c1.pesquisarNomes();
        for (cinetudo.Cinema nc : c2)
        {
            cb.insertItemAt(nc.getNome(), 0);
        }
        
    }
    
    public void limparTabela (DefaultTableModel modelo)
    {
        for( int i = modelo.getRowCount() - 1; i >= 0; i-- ) {
                modelo.removeRow(i);
        }        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        capc = new javax.swing.JTextField();
        pr = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idS = new javax.swing.JTextField();
        cb = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tp = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Consultar Sala");

        jButton1.setText("Consultar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo", "Capacidade", "Preco", "Cinema", "Codigo"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Capacidade:");

        jLabel3.setText("Preco:");

        jLabel2.setText("Codigo da sala:");

        idS.setEditable(false);

        jButton2.setText("Alterar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Cinema:");

        jLabel5.setText("Tipo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(pr, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(capc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cb, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(tp, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(idS, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(idS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(pr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(capc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       /* String titulo = tit.getText();
        cinetudo.Filme f1 = new cinetudo.Filme(titulo);
        f1.pesquisar();
        tit.setText(f1.getTitulo());
        dir.setText(f1.getDiretor());
        atp.setText(f1.getAtor());
        dur.setText(Integer.toString(f1.getDuracaoMin()));
        cla.setText(Integer.toString(f1.getFaixaEtaria()));
        cat.setText(f1.getCategoria());
        
        ArrayList<cinetudo.Sala> salas1 = new ArrayList<>();
        cinetudo.Cinema c1 = new cinetudo.Cinema(salas1);
        c1.pesquisar();
        for (cinetudo.Sala umaSala : salas1) {
            cap.insertItemAt(Integer.toString(umaSala.getCapacidade()), 0);
            pre.insertItemAt(Float.toString(umaSala.getPreco()), 0);
            id.insertItemAt(Integer.toString(umaSala.getNumero()), 0);
            nome.insertItemAt(umaSala.getCine(), 0);
        */
       
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        ArrayList<cinetudo.Sala> salas1 = new ArrayList<>();
        cinetudo.Cinema c1 = new cinetudo.Cinema(salas1);
        c1.pesquisar();
        limparTabela(modelo);
        Object rowData[] = new Object[5];
        for (cinetudo.Sala umaSala : salas1) {
            rowData[0] = umaSala.getTipoSala();
            rowData[1] = umaSala.getCapacidade();
            rowData[2] = umaSala.getPreco();
            rowData[3] = umaSala.getCine();
            rowData[4] = umaSala.getNumero();
            modelo.addRow(rowData);
        }  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int index = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        String tipo = model.getValueAt(index, 0).toString();
        String capacidade = model.getValueAt(index, 1).toString();
        String preco = model.getValueAt(index, 2).toString();
        String id = model.getValueAt(index, 4).toString();
       // String cinema = model.getValueAt(index, 3).toString();
        
        idS.setText(id);
        capc.setText(capacidade);
        pr.setText(preco);
        tp.setText(tipo);
       // cinemaNome.setText(cinema);
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        cinetudo.Cinema c = new cinetudo.Cinema();
        String nis,tipoS;
        tipoS = c.pesquisarTipo(Integer.parseInt(idS.getText()));
        if ("2D".equals(tipoS)){
            nis = cb.getSelectedItem().toString();
            c.pesquisar(nis);
            cinetudo.Sala s = new cinetudo.Sala2D(Integer.parseInt(idS.getText()),Integer.parseInt(capc.getText()));
            s.setTipoSala(tipoS);
            s.setCineCod(c.getI());
            int resposta = s.alterar();
        }
        if ("3D".equals(tipoS))
        {
            nis = cb.getSelectedItem().toString();
            c.pesquisar(nis);
            cinetudo.Sala s = new cinetudo.Sala3D(Integer.parseInt(idS.getText()),Integer.parseInt(capc.getText()));
            s.setCineCod(c.getI());
            s.setTipoSala(tipoS);
            int resposta = s.alterar();            
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField capc;
    private javax.swing.JComboBox<String> cb;
    private javax.swing.JTextField idS;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField pr;
    private javax.swing.JTextField tp;
    // End of variables declaration//GEN-END:variables
}


